config/routes.rb
Rails.application.routes.draw do
  



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to:'pages#home'
  get '/bonjour(/:name)', to:'pages#salut', as:'salut'
  resources :posts
  resources :categories
  
end

app/models/Post.rb
class Post < ApplicationRecord

include Sluggable;

belongs_to :category, counter_cache: true
has_and_belongs_to_many :tags
has_many :metas, as: :mettaable

scope :published, -> { where(online: true)}


validates :title, presence: { message: ' ne doit pas être vide'}









end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

has_many :posts
has_many :metas, as: :mettaable
end

app/models/concerns/sluggable.rb
module Sluggable

extend ActiveSupport::Concern
included do 
before_validation :set_default_slug, on: [:create, :update], if: '!slug.nil?'
validates :slug, format: { with: /\A[a-z0-9\-]+\z/}, uniqueness: true

private 
def set_default_slug
if !self.title.nil? &&  !self.title.empty? && self.slug.empty?
	self.slug = title.parameterize
end

end



end

end

app/models/meta.rb
class Meta < ApplicationRecord


belongs_to :mettaable, polymorphic: true
has_many :metas, as: :mettaable




end

app/models/tag.rb
class Tag < ApplicationRecord

has_and_belongs_to_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :danger
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :set_category, only: [:update, :edit, :show, :destroy]
  
  def index
  @session = session[ :user_id]
  @categories = Category.all
  end

  def show
  
  end

  def update
 
  @category.update(category_params)
  redirect_to category_path(@category.id)
  
  end

  def destroy
 
  @category.destroy
  redirect_to categories_path
  end

  def new
  @category= Category.new
  
  end
  
  def create
  @category= Category.create(category_params)
  redirect_to category_path(@category.id)
  end

  def edit
 
  
  
  end
  
  private
  
  def category_params
  params.require(:category).permit(:name, :slug)
end
 def set_category
 @category = Category.find(params[:id])
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def salut
@name=params[:name]
end

def home
ContactMailer.contact(Post.first).deliver_now
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :set_post, only: [:update, :edit, :show, :destroy]
  
  def index
 
  @posts=Post.includes( :category, :tags).all
  respond_to do |format|
	format.html
	format.json{render json: @posts}
		
	end
  end
  
  def show
   respond_to do |format|
   format.html
   format.json{render json: @post}
   end
  
  end
  
  def edit
 
  
  end
  
  def update
  
  if @post.update(post_params)
	redirect_to posts_path, success: "Article modifie avec succes"
   else
		render 'edit'
    end
  
  end
  
  def new
  @post = Post.new
  end
  
 def create
 post = Post.new(post_params)
 if post.valid?
	post.save
	redirect_to post_path(post.id), success: "Article crée avec succes"
 else
 @post = post
 render 'new'
 end

 end
 
 def destroy

 @post.destroy
 redirect_to posts_path, success: "Article supprimé avec succès"
 
 end
 
 private
 def post_params
 params.require(:post).permit(:title, :content, :slug, :category_id)
 end
 
 def set_post
 @post = Post.find(params[:id])
 end
 
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/gravatar_helper.rb
module GravatarHelper

def gravatar(email)
throw TypeError unless email.respond_to?(:to_s)



end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h1>Editer la categorie</h1>
<%= form_for @category do |f| %>
<div class="form-group">

<%= f.text_field :name,placeholder: 'Nom de la categorie', class: 'form-control' %>
</div>
<div class="form-group">

<%= f.text_area :slug,placeholder: 'URL', class: 'form-control'  %>
</div>
<div class="form-group">
<button type="submit" class="btn btn-primary">Modifier la categorie </button>
</div>

<% end %>

app/views/categories/index.html.erb
<h1>Les categories</h1>


<table class="table">
<thead>
<tr>
<td>ID</td>
<td>Nom</td>
<td>Actions</td>
</tr>

</thead>
<tbody>






<% @categories.each do |category| %> 
<tr>
<td><%= category.id %></td>
<td><%= category.name %></td>
<td>
<a href="<%= edit_category_path(category.id)%>" class="btn btn-primary">Editer</a>
<a href="<%= category_path(category.id)%>" class="btn btn-danger" data-confirm="Are you sure ?" data-method="delete">Supprimer</a>
</td>
</tr>

<% end %>
</tbody>

</table>
<p>
<a href="<%= new_category_path %>" class="btn btn-success">Ajouter une categorie</a>
</p>

app/views/categories/new.html.erb
<h1>Nouvelle categorie</h1>
<%= form_for @category do |f| %>
<div class="form-group">

<%= f.text_field :name,placeholder: 'Nom de la categorie', class: 'form-control' %>
</div>
<div class="form-group">

<%= f.text_area :slug,placeholder: 'URL', class: 'form-control'  %>
</div>
<div class="form-group">
<button type="submit" class="btn btn-primary">Creer la categorie </button>
</div>

<% end %>

app/views/categories/show.html.erb
<h1> <%=@category.name %></h1>

<p><%= @category.slug %> </p>

<p>
<a href="<%= categories_path%>" class="btn btn-primary">Revenir aux categories</a>
</p>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body>
     <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="<%=root_path%>">Ruby On Rails</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="<%=posts_path%>">Articles <span class="sr-only">(current)</span></a>
          </li>
		  <li class="nav-item active">
		  <a class="nav-link" href="<%=categories_path%>">Categories <span class="sr-only">(current)</span></a>
		  </li>
         
          
        </ul>
        
    </nav>
	<div class="container" style="padding-top:5rem">
	<% if flash[:success] %>
	<div class="alert alert-success"><%= flash[:success] %></div>
	<% end %>
    <%= yield %>
	</div>
  </body>
</html>

app/views/pages/home.html.erb
<h1> Bienvenue sur le site </h1>

<%= image_tag 'ruby_logo.png', width: 100 %>

app/views/pages/salut.html.erb
Salut <%=@name %>, comment ca va 

app/views/posts/_form.html.erb
<% if post.errors.any? %>
	<div class="alert alert-danger">
	<% post.errors.full_messages.each do |message| %>
	<%= message %>
	
	<% end %>
	</div>
<% end %>

<%= form_for post do |f| %>
<div class="form-group">
<label>Titre de l'article </label>
<%= f.text_field :title, class: 'form-control' %>
</div>
<div class="form-group">
<label>URL de l'article </label>
<%= f.text_field :slug, class: 'form-control' %>
</div>
<div class="form-group">
<label for="category">Categorie </label>
<%= f.select :category_id, Category.pluck(:name, :id) %>
</div>
<div class="form-group">
<label>Contenu de l'article </label>
<%= f.text_area :content, class: 'form-control' %>
</div>
<div class="form-group">
<button type="submit" class="btn btn-primary">Modifier l'article </button>
</div>





</div>

<% end %>

app/views/posts/edit.html.erb
<h1> Editer l'article </h1>

<%= render  'form', post: @post %>

app/views/posts/index.html.erb
<h1>Articles du blog</h1>

<% @posts.each do |post| %> 
<h2><%=post.title%></h2>
<p><%=post.content%></p>
<% if post.category %>
<p>Categorie : <%=post.category.name %></p>
<% end %>
<p>
Tags : 
<% post.tags.each do |tag| %>
<%= tag.name %>
<% end %>
</p>

<p>
<a href="<%= post_path(post.id)%>" class="btn btn-primary">Lire la suite</a>
<a href="<%= edit_post_path(post.id)%>" class="btn btn-default">Editer</a>
<a href="<%= post_path(post.id)%>" class="btn btn-danger" data-confirm= "Etes-vous sûr ?" data-method= "DELETE">Supprimer</a>

</p>
<hr />



<%end%>
<p>
<a href="<%= new_post_path %>" class="btn btn-success">Ajouter un article</a>
</p>

app/views/posts/new.html.erb
<h1> Creer un article </h1>

<%= render  'form', post: @post %>

app/views/posts/show.html.erb
<% content_for(:title, @post.title) %>

<h1> <%=@post.title %></h1>

<p><%= @post.content %> </p>

<p>
<a href="<%= posts_path%>" class="btn btn-primary">Revenir aux articles</a>
</p>